### ISSUE TITLE
Can't install the library

### ISSUE THREAD

**Issue by Svito-zar** [YannickJadoul/Parselmouth#10] opened 2019-01-16 09:37 UTC
I am using Linux OS (Ubuntu 16.04) and Python version 3.5.

I have just installed the library (on my Anaconda virtenv) and I am getting an error when trying to import it:

``` python
import parselmouth
```

"Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/taras/anaconda3/envs/CondaEnvPy3Tf/lib/python3.5/site-packages/parselmouth/__init__.py", line 22, in <module>
    from parselmouth.base import Parselmouth
  File "/home/taras/anaconda3/envs/CondaEnvPy3Tf/lib/python3.5/site-packages/parselmouth/base.py", line 30, in <module>
    from parselmouth.adapters.dfp.interface import DFPInterface
  File "/home/taras/anaconda3/envs/CondaEnvPy3Tf/lib/python3.5/site-packages/parselmouth/adapters/dfp/interface.py", line 17, in <module>
    from urllib import quote
ImportError: cannot import name 'quote' "

**Comment by YannickJadoul** [comment] 2019-01-16 09:59
@Svito-zar I believe you might have `pip install`ed the `parselmouth` package, instead of `praat-parselmouth`? Unfortunately the previous name was already taken on the Python Package Index, so the package name vs. project name is slightly confusing. Apologies for that, but nothing I can do anything about, as far as know :-(

Can you confirm whether this is the case, or whether something else is wrong?

**Comment by Svito-zar** [comment] 2019-01-16 10:52
Yes, that indeed was an issue

**Comment by YannickJadoul** [comment] 2019-01-16 11:14
OK, I'll close this issue, then, if it is indeed resolved.

**Closed by YannickJadoul** 2019-01-16 11:14 UTC

**Comment by jyothika12** [comment] 2019-06-20 14:22
hi i am also having the same issue .. i have pip installed praat parselmouth only but still.
ImportError: cannot import name 'quote' from 'urllib' (C:\Users\Jyotika Patwardhan\AppData\Local\Programs\Python\Python37-32\lib\urllib\__init__.py)

**Comment by YannickJadoul** [comment] 2019-06-20 14:35
@jyothika12 Is it the same problem? Have you `pip install`ed  `parselmouth` instead of `praat-parselmouth`? (cfr. https://parselmouth.readthedocs.io/en/stable/installation.html)

Then the same solution should also work, I hope?

**Comment by jyothika12** [comment] 2019-06-21 09:30
It is the same problem . I have pip installed praat-parselmouth only .

**Comment by YannickJadoul** [comment] 2019-06-21 10:03
@jyothika12 Hmmm, weird. Two things:
- Can you run `pip uninstall parselmouth` and see what happens?
- If that doesn't help: could you copy-paste the full traceback of the error you're getting, instead of just the last line? Then we see where the error originates.

**Comment by jyothika12** [comment] 2019-06-22 07:22
*after reinstalling it now I am getting this error*.

C:\Users\Jyotika Patwardhan>pip uninstall praat-parselmouth
Uninstalling praat-parselmouth-0.3.3:
  Would remove:
    c:\users\jyotika
patwardhan\appdata\local\programs\python\python37-32\lib\site-packages\parselmouth.cp37-win32.pyd
    c:\users\jyotika
patwardhan\appdata\local\programs\python\python37-32\lib\site-packages\praat_parselmouth-0.3.3.dist-info\*
Proceed (y/n)? y
  Successfully uninstalled praat-parselmouth-0.3.3

C:\Users\Jyotika Patwardhan>pip install praat-parselmouth
Collecting praat-parselmouth
  Using cached
https://files.pythonhosted.org/packages/3b/32/f344046db6759ed2b3939f7671caf469ad15489dfe97c56b37807d4c4232/praat_parselmouth-0.3.3-cp37-cp37m-win32.whl
Requirement already satisfied: numpy>=1.7.0 in c:\users\jyotika
patwardhan\appdata\local\programs\python\python37-32\lib\site-packages
(from praat-parselmouth) (1.16.4)
Installing collected packages: praat-parselmouth
Successfully installed praat-parselmouth-0.3.3


C:\Users\Jyotika Patwardhan\PycharmProjects\Demo_1\venv\Scripts\python.exe"
"C:/Users/Jyotika Patwardhan/.PyCharmCE2018.3/config/scratches/scratch.py"
Traceback (most recent call last):
  File "C:/Users/Jyotika
Patwardhan/.PyCharmCE2018.3/config/scratches/scratch.py", line 1, in
<module>
    import parselmouth
ImportError: DLL load failed: %1 is not a valid Win32 application.

Process finished with exit code 1

**Comment by jyothika12** [comment] 2019-06-22 07:28
I am also checked for broken dependencies.

C:\Users\Jyotika Patwardhan>pip check parselmouth
No broken requirements found.

**Comment by jyothika12** [comment] 2019-06-22 08:04
*If i am trying to import using pycharm i am getting the following error :*

C:\Users\Jyotika Patwardhan\PycharmProjects\Demo_1\venv\Scripts\python.exe"
"C:/Users/Jyotika Patwardhan/.PyCharmCE2018.3/config/scratches/scratch.py"
Traceback (most recent call last):
  File "C:/Users/Jyotika
Patwardhan/.PyCharmCE2018.3/config/scratches/scratch.py", line 1, in
<module>
    import parselmouth
ImportError: DLL load failed: %1 is not a valid Win32 application.

Process finished with exit code 1

*if i am trying to import using python in command prompt then i am getting
the following error  :*

import parselmouth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'parselmouth'

**Comment by YannickJadoul** [comment] 2019-06-22 18:37
@jyothika12 We're already making progress, then, if it doesn't have the other issue anymore :-)

I think this problem occurs because of multiple versions of Python you have installed, where one is 32-bit and the other is 64-bit. I checked the versions of Parselmouth, and as far as I can see, these are correctly 32 and 64-bit. So my current guess is that your `pip` somehow installs a 32-bit version of Parselmouth into the directory that contains libraries for your 64-bit version.

Relevant StackOverflow answers, I found:
https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls
https://stackoverflow.com/questions/43434028/how-to-pip-install-64-bit-packages-while-having-both-64-bit-and-32-bit-versions

Could you, please:
- Report the output of running `pip --version` and `where python` in the terminal?
- Report the output you get when starting Python, both in the terminal as well as in PyCharm? I mean the lines that look something like this, and tell me whether it's 32-bit or 64-bit:
    ```
    Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
    [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    ```
- Report the output of running `python -m site` and `C:\Users\Jyotika Patwardhan\PycharmProjects\Demo_1\venv\Scripts\python.exe -m sit` in your terminal.

Sorry for all these questions and that I don't have an answer yet, but I need to get this info to see what's going wrong. I hope that once I have this information about the different Python versions on your computer, I can confirm that nothing's wrong with Parselmouth, and give you the command to get the installation fixed :-)

**Comment by jyothika12** [comment] 2019-06-24 12:51
C:\Windows\system32>pip --version
pip 19.1.1 from c:\users\jyotika
patwardhan\appdata\local\programs\python\python37-32\lib\site-packages\pip
(python 3.7)

C:\Windows\system32>where python
C:\Program Files (x86)\PsychoPy3\python.exe
C:\Users\Jyotika
Patwardhan\AppData\Local\Programs\Python\Python37-32\python.exe

C:\Windows\system32>python -m site
sys.path = [
    'C:\\Windows\\system32',
    'C:\\Program Files (x86)\\PsychoPy3\\python36.zip',
    'C:\\Program Files (x86)\\PsychoPy3\\DLLs',
    'C:\\Program Files (x86)\\PsychoPy3\\lib',
    'C:\\Program Files (x86)\\PsychoPy3',
    'C:\\Program Files (x86)\\PsychoPy3\\lib\\site-packages',
    'C:\\Program Files (x86)\\PsychoPy3\\lib\\site-packages\\win32',
    'C:\\Program Files (x86)\\PsychoPy3\\lib\\site-packages\\win32\\lib',
    'C:\\Program Files (x86)\\PsychoPy3\\lib\\site-packages\\Pythonwin',
]
USER_BASE: 'C:\\Users\\Jyotika Patwardhan\\AppData\\Roaming\\Python'
(doesn't exist)
USER_SITE: 'C:\\Users\\Jyotika
Patwardhan\\AppData\\Roaming\\Python\\Python36\\site-packages' (doesn't
exist)
ENABLE_USER_SITE: True

C:\Windows\system32>C:\Users\Jyotika
Patwardhan\PycharmProjects\Demo_1\venv\Scripts\python.exe -m sit
'C:\Users\Jyotika' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jyothika12** [comment] 2019-06-24 12:56
*on terminal*

C:\Users\Jyotika Patwardhan>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit
(AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

*on pycharm*

PyDev console: starting.
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32
bit (Intel)] on win32

**Comment by YannickJadoul** [comment] 2019-06-24 13:06
@jyothika12 Right, so there are indeed (at least) two Python versions, one saying '64 bit (AMD64)', while the other says '32 bit (Intel)' :-) Thank you very much for confirming that!

I would suggest uninstalling Parselmouth one last time. Then go into the Python interpreter shell where you want to use Parselmouth, and run:

```pycon
>>> import subprocess, sys
>>> subprocess.call([sys.executable, "-m", "pip", "install", "-U", "--force-reinstall", "praat-parselmouth"])
...
```

(You can also see https://parselmouth.readthedocs.io/en/stable/installation.html#multiple-python-versions for more details, or other ways of fixing multiple installed Python versions :-) )

**Comment by YannickJadoul** [comment] 2019-06-24 13:10
(If this doesn't work, do let me know; but I think this should do the trick, using `sys.executable` to get the right version of Python and pip)

**Comment by jyothika12** [comment] 2019-06-24 13:59
hi ,

In pycharm i am not able to use import command . and i dont know what can
be the issue the environment variables are also set .
every time i use import command i get the folowing error
'import' is not recognized as an internal or external command,
operable program or batch file.

can you please help me with that

**Comment by YannickJadoul** [comment] 2019-06-24 14:10
@jyothika12 Are you running this in the "Python Console" of PyCharm, and not in the "Terminal"?
The lines I sent must be executed inside of Python.

**Comment by jyothika12** [comment] 2019-06-24 14:14
I am running this inside pycharm terminal

**Comment by YannickJadoul** [comment] 2019-06-24 14:15
> I am running this inside pycharm terminal

Then either run in the in the PyCharm Python console, or run `python` first inside the PyCharm Terminal

**Comment by jyothika12** [comment] 2019-06-24 14:43
thanks YannickJadoul/Parselmouth
 i have uninstalled parselmouth ,python, pycharm and reinstalled
everything. and now its working . maybe some settings were wrong and now
your command has worked . thankyou.

**Comment by jyothika12** [comment] 2019-06-24 14:52
import subprocess, sys
subprocess.call([sys.executable, "-m", "pip", "install", "-U",
"--force-reinstall", "praat-parselmouth"])
Collecting praat-parselmouth
  Using cached
https://files.pythonhosted.org/packages/3b/32/f344046db6759ed2b3939f7671caf469ad15489dfe97c56b37807d4c4232/praat_parselmouth-0.3.3-cp37-cp37m-win32.whl
Collecting numpy>=1.7.0 (from praat-parselmouth)
  Using cached
https://files.pythonhosted.org/packages/07/46/656c25b39fc152ea525eef14b641993624a6325a8ae815b200de57cff0bc/numpy-1.16.4-cp37-cp37m-win32.whl
Installing collected packages: numpy, praat-parselmouth
Successfully installed numpy-1.16.4 praat-parselmouth-0.3.3
0
import parselmouth
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition
2019.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in
do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by jyothika12** [comment] 2019-06-24 14:53
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by YannickJadoul** [comment] 2019-06-24 15:40
@jyothika12 So it has not worked? :-(
Sorry; I will try this out on a Windows machine I have access to, now, and see if I can get the same error :-/

**Comment by jyothika12** [comment] 2019-06-24 16:01
Thanks

**Comment by YannickJadoul** [comment] 2019-06-24 16:05
Let's continue the discussion in the new #18 issue?

**Comment by Fallarcomigo** [comment] 2020-09-06 17:34
Hi there, 

I'm new to praat, however, initiated the installation of parselmouth in anaconda3 python. And found out that module Praat doesnt exist in the parselmouth package to use the call function. can someone help please.

im getting an era below when i perform (from parselmouth.Praat import call)

ModuleNotFoundError: No module named 'parselmouth.Praat'; 'parselmouth' is not a package

**Comment by YannickJadoul** [comment] 2020-09-06 17:44
@Fallarcomigo This seems like another issue than the original issue, so it is maybe better to start another thread (or quickly ask on [Gitter](https://gitter.im/PraatParselmouth/Lobby)).

I think the problem is the capital in what you write. It's `from parselmouth.praat import call`, not `Praat`.
If you did that correctly, then can you say whether you can `import parselmouth` and `print(parselmouth.Sound)`. Does that give errors, and which ones?

**Comment by Fallarcomigo** [comment] 2020-09-06 17:52
thank you so much.that was the problem, it works well now.

**Comment by YannickJadoul** [comment] 2020-09-06 18:23
Great! Thanks for letting me know, @Fallarcomigo :)

**Comment by BarbaraChow** [comment] 2024-09-25 14:39
Sorry to bother you. I am using Window64 and Python version 3.6.3

I am getting an error when run: snd = parselmouth.Sound("audio/the_north_wind_and_the_sun.wav")

AttributeError: module 'parselmouth' has no attribute 'Sound'

**Comment by YannickJadoul** [comment] 2024-09-26 13:45
@BarbaraChow, how did you install Parselmouth? Are you running into the same issue as above, where you did `pip install parselmouth` instead of `pip install praat-parselmouth`? If so, you need to `pip uninstall parselmouth` then `pip install praat-parselmouth`.

Apart from that, do know that Python 3.6 is out of support meanwhile (see https://endoflife.date/python; latest supported version is currently 3.8). Parselmouth still offers builds for 3.6 for Parselmouth 0.4.4, but won't anymore for the next minor version release.

**Comment by BarbaraChow** [comment] 2024-09-29 09:56
Yes, I encountered the same issue as above, so I did `pip uninstall parselmouth` then `pip install praat parselmouth`, but the error still exist. But when I reboot my computer, and now its working.
